spring.application.name=escadas

# Força o Thymeleaf a ler os arquivos HTML em UTF-8
spring.thymeleaf.encoding=UTF-8

spring.web.error.include-message=always

# Inclui o Stack Trace completo na resposta JSON/HTML
spring.web.error.include-stacktrace=always

# Mostra erros de validação (Binding Errors) detalhados
spring.web.error.include-binding-errors=always

# (Opcional) Mostra qual foi a classe da exceção
spring.web.error.include-exception=true

spring.profiles.active=dev

# Configurações do Hibernate / JPA
# "update" cria ou atualiza as tabelas automaticamente baseado nas suas Entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liga as cores no terminal (ajuda MUITO a bater o olho e achar o erro)
spring.output.ansi.enabled=ALWAYS

# Formato mais limpo para o console (Terminal da sua IDE)
# Mostra: [Hora] [Nível] [Sua Classe] - A mensagem
logging.pattern.console=%d{HH:mm:ss} %clr(%-5level) %cyan(%-40.40logger{39}) : %msg%n

# Formato idêntico para o arquivo de log (que o Spring Boot Admin vai ler)
logging.pattern.file=%d{HH:mm:ss} %-5level %-40.40logger{39} : %msg%n

logging.file.name=logs/app.log