spring.application.name=escadas

# Força o Thymeleaf a ler os arquivos HTML em UTF-8
spring.thymeleaf.encoding=UTF-8

spring.web.error.include-message=always

# Inclui o Stack Trace completo na resposta JSON/HTML
spring.web.error.include-stacktrace=always

# Mostra erros de validação (Binding Errors) detalhados
spring.web.error.include-binding-errors=always

# (Opcional) Mostra qual foi a classe da exceção
spring.web.error.include-exception=true

spring.profiles.active=dev