# Configurações de Produção para JPA/Hibernate e MySQL
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false

# Suporte a cabeçalhos de Proxy Reverso (Cloudflare / Nginx)
server.forward-headers-strategy=framework
server.tomcat.remoteip.remote-ip-header=CF-Connecting-IP
server.tomcat.remoteip.protocol-header=X-Forwarded-Proto
