package com.example.demo.pedidos.config;

import com.example.demo.shared.crud.OpcaoCrud;
import com.example.demo.shared.crud.formulario.CampoFormularioCrud;
import com.example.demo.shared.crud.formulario.CamposFormularioCrud;

import java.util.List;

public class FormularioPedidoViewConfig {

    public static List<CampoFormularioCrud> criarCampos(
            List<OpcaoCrud> opcoesUf,
            List<OpcaoCrud> opcoesUfCliente,
            List<OpcaoCrud> opcoesBairro,
            List<OpcaoCrud> opcoesBairroCliente,
            List<OpcaoCrud> opcoesMunicipio,
            List<OpcaoCrud> opcoesMunicipioCliente
    ) {
        return List.of(
                CamposFormularioCrud.numero(
                        ColunasPedido.CAMPO_NUMERO_PEDIDO,
                        ColunasPedido.LABEL_NUMERO_PEDIDO,
                        null,
                        true,
                        "1",
                        null,
                        "campo--numero-pedido"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_CLIENTE_NOME,
                        ColunasPedido.LABEL_CLIENTE_NOME,
                        null,
                        true,
                        120,
                        "campo--cliente-nome"
                ),
                CamposFormularioCrud.email(
                        ColunasPedido.CAMPO_EMAIL,
                        ColunasPedido.LABEL_EMAIL,
                        null,
                        false,
                        120,
                        "campo--email"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_CPF,
                        ColunasPedido.LABEL_CPF,
                        null,
                        false,
                        14,
                        "campo--cpf"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_RG,
                        ColunasPedido.LABEL_RG,
                        null,
                        false,
                        12,
                        "campo--rg"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_CNPJ,
                        ColunasPedido.LABEL_CNPJ,
                        null,
                        false,
                        30,
                        "campo--cnpj"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_SERVICO_SOCIAL,
                        ColunasPedido.LABEL_SERVICO_SOCIAL,
                        null,
                        false,
                        100,
                        "campo--servico-social"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_PROFISSAO,
                        ColunasPedido.LABEL_PROFISSAO,
                        null,
                        false,
                        100,
                        "campo--profissao"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_ADM_OBRA,
                        ColunasPedido.LABEL_ADM_OBRA,
                        null,
                        false,
                        100,
                        "campo--adm-obra"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_TELEFONE,
                        ColunasPedido.LABEL_TELEFONE,
                        null,
                        false,
                        20,
                        "campo--telefone"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_TELEFONE_FIXO,
                        ColunasPedido.LABEL_TELEFONE_FIXO,
                        null,
                        false,
                        20,
                        "campo--telefone-fixo"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_ACABAMENTO,
                        ColunasPedido.LABEL_ACABAMENTO,
                        null,
                        false,
                        120,
                        "campo--acabamento"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_TUBOS,
                        ColunasPedido.LABEL_TUBOS,
                        null,
                        false,
                        120,
                        "campo--tubos"
                ),
                CamposFormularioCrud.selecao(
                        ColunasPedido.CAMPO_REVESTIMENTO,
                        ColunasPedido.LABEL_REVESTIMENTO,
                        false,
                        List.of(new OpcaoCrud("true", "Sim"), new OpcaoCrud("false", "Não")),
                        "campo--revestimento"
                ),
                CamposFormularioCrud.numero(
                        ColunasPedido.CAMPO_VALOR_TOTAL,
                        ColunasPedido.LABEL_VALOR_TOTAL,
                        null,
                        false,
                        "0",
                        "0.01",
                        "campo--valor-total"
                ),
                CamposFormularioCrud.numero(
                        ColunasPedido.CAMPO_PRAZO_MONTAGEM,
                        ColunasPedido.LABEL_PRAZO_MONTAGEM,
                        null,
                        false,
                        "0",
                        null,
                        "campo--prazo-montagem"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_NUMERO,
                        ColunasPedido.LABEL_NUMERO,
                        null,
                        false,
                        10,
                        "campo--numero"
                ),
                CamposFormularioCrud.selecao(
                        ColunasPedido.CAMPO_UF,
                        ColunasPedido.LABEL_UF,
                        true,
                        opcoesUf,
                        "campo--uf"
                ),
                CamposFormularioCrud.selecao(
                        ColunasPedido.CAMPO_MUNICIPIO,
                        ColunasPedido.LABEL_MUNICIPIO,
                        false,
                        opcoesMunicipio,
                        "campo--municipio"
                ),
                CamposFormularioCrud.selecao(
                        ColunasPedido.CAMPO_BAIRRO,
                        ColunasPedido.LABEL_BAIRRO,
                        false,
                        opcoesBairro,
                        "campo--bairro"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_CEP,
                        ColunasPedido.LABEL_CEP,
                        null,
                        false,
                        9,
                        "campo--cep"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_REFERENCIA,
                        ColunasPedido.LABEL_REFERENCIA,
                        null,
                        false,
                        200,
                        "campo--referencia"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_NUMERO_CLIENTE,
                        ColunasPedido.LABEL_NUMERO_CLIENTE,
                        null,
                        false,
                        10,
                        "campo--numero-cliente"
                ),
                CamposFormularioCrud.selecao(
                        ColunasPedido.CAMPO_UF_CLIENTE,
                        ColunasPedido.LABEL_UF_CLIENTE,
                        true,
                        opcoesUfCliente,
                        "campo--uf-cliente"
                ),
                CamposFormularioCrud.selecao(
                        ColunasPedido.CAMPO_MUNICIPIO_CLIENTE,
                        ColunasPedido.LABEL_MUNICIPIO_CLIENTE,
                        false,
                        opcoesMunicipioCliente,
                        "campo--municipio-cliente"
                ),
                CamposFormularioCrud.selecao(
                        ColunasPedido.CAMPO_BAIRRO_CLIENTE,
                        ColunasPedido.LABEL_BAIRRO_CLIENTE,
                        false,
                        opcoesBairroCliente,
                        "campo--bairro-cliente"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_CEP_CLIENTE,
                        ColunasPedido.LABEL_CEP_CLIENTE,
                        null,
                        false,
                        9,
                        "campo--cep-cliente"
                ),
                CamposFormularioCrud.texto(
                        ColunasPedido.CAMPO_REFERENCIA_CLIENTE,
                        ColunasPedido.LABEL_REFERENCIA_CLIENTE,
                        null,
                        false,
                        200,
                        "campo--referencia-cliente"
                ),
                CamposFormularioCrud.numero(
                        ColunasPedido.CAMPO_VALOR,
                        ColunasPedido.LABEL_VALOR,
                        null,
                        false,
                        "0",
                        "0.01",
                        "campo--valor"
                ),
                CamposFormularioCrud.textarea(
                        ColunasPedido.CAMPO_DESCRICAO,
                        ColunasPedido.LABEL_DESCRICAO,
                        null,
                        false,
                        4,
                        2000,
                        "filtro-crud--completo campo--descricao"
                )
        );
    }
}